const BS=["http://127.0.0.1:8765","http://localhost:8765"];let attachedTabId=null,pollTimer=null;
async function bridge(p,o={}){let e;for(const b of BS){try{let r=await fetch(b+p,o);if(!r.ok)throw Error("HTTP "+r.status);return await r.json()}catch(x){e=x}}throw e||Error("bridge unavailable")}
async function status(x){try{await bridge("/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(x)})}catch(e){console.warn(e)}}
async function attach(id){let t=await chrome.tabs.get(id);if(!(t.url||"").includes("doomsol.com"))throw Error("Selected tab is not doomsol.com.");await bridge("/status");if(attachedTabId!==null&&attachedTabId!==id)try{await chrome.debugger.detach({tabId:attachedTabId})}catch(_){}
try{await chrome.debugger.attach({tabId:id},"1.3")}catch(e){throw Error("Brave debugger attach failed: "+(e.message||e))}
attachedTabId=id;await chrome.debugger.sendCommand({tabId:id},"Page.enable");await chrome.debugger.sendCommand({tabId:id},"Runtime.enable");await status({attached:true,tabId:id,title:t.title||"",url:t.url});start();return{ok:true}}
async function detach(){if(attachedTabId!==null)try{await chrome.debugger.detach({tabId:attachedTabId})}catch(_){}attachedTabId=null;await status({attached:false});return{ok:true}}
async function capture(c={}){if(attachedTabId===null)return;let r=await chrome.debugger.sendCommand({tabId:attachedTabId},"Page.captureScreenshot",{format:"jpeg",quality:70,fromSurface:true});await bridge("/frame",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tabId:attachedTabId,data:r.data,timestamp:Date.now(),requestId:c.requestId||null})})}
async function input(c){if(attachedTabId===null)return;let q={tabId:attachedTabId};if(c.type==="key")await chrome.debugger.sendCommand(q,"Input.dispatchKeyEvent",{type:c.down?"keyDown":"keyUp",key:c.key,code:c.code||c.key,windowsVirtualKeyCode:c.vk,nativeVirtualKeyCode:c.vk});else if(c.type==="mouse")await chrome.debugger.sendCommand(q,"Input.dispatchMouseEvent",{type:c.event||"mouseMoved",x:c.x,y:c.y,button:c.button||"none",buttons:c.buttons||0,deltaX:c.deltaX||0,deltaY:c.deltaY||0});else if(c.type==="click"){for(const type of["mousePressed","mouseReleased"])await chrome.debugger.sendCommand(q,"Input.dispatchMouseEvent",{type,x:c.x,y:c.y,button:"left",clickCount:1,buttons:type==="mousePressed"?1:0})}
else if(c.type==="eval"){let r=await chrome.debugger.sendCommand(q,"Runtime.evaluate",{expression:c.expression,returnByValue:true,awaitPromise:true});await bridge("/eval-result",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,result:r.result||null,exceptionDetails:r.exceptionDetails||null})})}
}
async function poll(){if(attachedTabId===null)return;try{for(const c of(await bridge("/commands")).commands||[])c.type==="capture"?await capture(c):await input(c)}catch(e){console.warn(e)}}
function start(){if(!pollTimer)pollTimer=setInterval(poll,40)}
chrome.runtime.onMessage.addListener((m,s,reply)=>{(async()=>{try{reply(m.type==="attach"?await attach(m.tabId):m.type==="detach"?await detach():{ok:false,error:"Unknown command"})}catch(e){console.error(e);reply({ok:false,error:e.message||String(e)})}})();return true});
// Intentionally no chrome.debugger.onDetach listener. Some Brave builds omit this event.
